#!/bin/bash

# Gather system information
USERNAME=$(whoami)
DATE=$(date)
HOSTNAME=$(hostname)
OS=$(. /etc/os-release && echo "$PRETTY_NAME")
UPTIME=$(uptime -p)

# Gather hardware information
CPU=$(lshw -short | grep -i processor | awk '{$1=$2=""; print $0}' | sed 's/^ *//')
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISKS=$(lsblk -d -o model,size | tail -n +2)
VIDEO=$(lshw -short | grep -i display | awk '{$1=$2=""; print $0}' | sed 's/^ *//')

# Gather network information
FQDN=$(hostname -f)
HOST_ADDRESS=$(ip -4 a | grep -oP '(?<=inet\s)\d+\.\d+\.\d+\.\d+' | head -1)
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep 'nameserver' | awk '{print $2}' | head -1)

# Gather system status information
USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | paste -sd ",")
DISK_SPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}')
PROCESS_COUNT=$(ps aux --no-heading | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d':' -f2 | sort -n | uniq | paste -sd ",")
UFW_STATUS=$(sudo ufw status | grep -i "Status:" | awk '{print $2}')

# Output report using EOF
cat << EOF

System Report generated by $USERNAME, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disks:
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
